- name: Build Web Project
  run: msbuild src/BugTracker.Web/BugTracker.Web.csproj /p:Configuration=Release /p:Platform="Any CPU"

- name: Build Windows Service
  run: msbuild src/btnet_service/btnet_service.csproj /p:Configuration=Release /p:Platform="Any CPU"

- name: Build Console App
  run: msbuild src/btnet_service/btnet_console.csproj /p:Configuration=Release /p:Platform="Any CPU"
